### ISSUE TITLE
GH Actions or Travis CI pipeline implementation

### ISSUE THREAD

**Issue by kjczarne** [Technica-Engineering/kalash#1]
We need to migrate our old GitLab CI pipeline to something supported in GitHub.

**Comment by kjczarne** [comment]
Note: we are already providing an acceptable way of accessing documentation, albeit a bit lousy and we should host the build docs soon.

But we need to consider publishing code coverage reports on top of that as a part of our quality assurance process.

**Comment by kayoub5** [comment]
My recommendations

### Automated Code Review
https://github.com/marketplace?category=code-quality&query=sort%3Apopularity-desc&type=&verification=

### Code Coverage
* https://about.codecov.io/

### CI
* Just Works: GitHub Actions, unless you have specific needs, just go with this
* Fast: Circle CI
* Not Docker based (For Npcap or WinPcap to work): Azure Pipelines
* Multiple CPU Architectures (ARM): Travis

**Comment by kjczarne** [comment]
@kayoub5 Thanks for the tips! For CI we're currently leaning towards GH actions since this tool has no dependency on any network drivers or any particular devices. CodeCov looks like a nice option to publish coverage, thanks!

**Comment by kjczarne** [comment]
@kayoub5, I've requested access to `codecov.io` scoped to this project. A basic implementation of GitHub Actions pipeline is also ready. This project has a fairly simple test-and-deploy pipeline so I feel like GH Actions is sufficient at least at the moment.

**Comment by kayoub5** [comment]
Access granted

**Comment by kjczarne** [comment]
That was fast! 😮 Thank you!

**Comment by kayoub5** [comment]
You're welcome.

**Comment by kjczarne** [comment]
Basic GH Actions pipeline implemented. Code coverage published with Codecov.io
