### ISSUE TITLE
[FEATURE] JSON support

### ISSUE THREAD

**Issue by kjczarne** [Technica-Engineering/kalash#8]
**Is your feature request related to a problem? Please describe.**
#7 - this means we can win JSON support _for free_. 

**Describe the solution you'd like**
- [x] ~Use built-in JSON module as an alternative to YAML~
- [x] ~Create a test for a JSON config~
- [x] Reuse the JSON/YAML schema (#7)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kayoub5** [comment]
@kjczarne I am not sure if you are aware, but any valid JSON is also valid YAML, so you can use the yaml parser to also parse JSON

**Comment by kjczarne** [comment]
@kayoub5 yes, the packages in Python are separate for YAML and JSON but they yield the identical data structure. All I need to do is use the `json` module on JSON files and `pyyaml` on YAML files and feed it directly to the data model. And hence we can use the JSON schema (#7) to validate both YAML and JSON at the same time 😉

**Comment by kayoub5** [comment]
@kjczarne you don't get what I mean, `yaml.parse` accept json input

**Comment by kjczarne** [comment]
Hmm, I wasn't aware of that. I'll try parsing a JSON with pyyaml then to check.

**Comment by kjczarne** [comment]
Ok, this is embarrassing. It works perfectly. Years of developing in Python and I didn't know PyYaml had this ability 😆
